# name: Build pdoc container and push to ghcr.io

# on:
#   push:
#     branches: master

# jobs:
#   github-ghcr:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v2
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#         with:
#           driver-opts: image=moby/buildkit:master
#       -
#         name: Login to GitHub Container Registry
#         if: github.event_name != 'pull_request'
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.CR_PAT }}
#       -
#         name: Build
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           platforms: linux/amd64
#           push: ${{ github.event_name != 'pull_request' }}
#           tags: ghcr.io/ramprasad-group/polymer_smiles:latest