name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Set up Python
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        pip install poetry
        poetry install      
    - name: Run tests in tests/ with pytest
      run: |
        poetry run pytest --exitfirst --verbose --failed-first